### ISSUE TITLE
Appears to build to static URLs making it unmovable to another URL or service

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-js#10]
The "yarn build" generates static HREFs (or incorrect HREFs) in the index.html restricting the JS App from being moved to another part of a URL tree.

Requires manually editing of the index.html to allow dynamic HREFs

**Comment by garethsb-sony** [comment]
Looks like @rufusu-sony removed `"homepage": "."` from the package.json in the last PR, which I suspect was inadvertent.

**Comment by garethsb-sony** [comment]
Should be fixed by b8772428e1164b949c13f3cb0163f77f8c52ea8d. Thanks for the report, Rich.
