### ISSUE TITLE
Feature Request - Option to patch a chosen leg to single legged receiver

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-js#38]
Currently nmos-js always patches the primary leg to a single legged receiver. It would be great for a single-legged receiver to have the option to patch either a senders primary or secondary leg to it...

This is particularly useful for monitoring or analysis receivers...

I'm not sure how best to implement this but possibly a Connect-Pri/Connect-Sec etc. approach for dual-legged senders connecting to single-legged receivers?

An alternative, which is less flexible but might be easier to do? If the primary leg is rtp_enabled:false on the sender then secondary leg is patched to the single-legged receiver on connection...?

**Comment by garethsb-sony** [comment]
> This is particularly useful for monitoring or analysis receivers...

Thank you for including the user story.

> how best to implement this 

In terms of user interface, I suggest a pop-up menu on the **Receiver > Connect** tab's **Stage** and **Activate** buttons that offers Primary and Secondary is the simplest. It would only appear in the case of connecting a two-legged ST 2022-7 Sender to a one-legged Receiver. (We already use a similar menu for the **Connect** button on the **Settings > Query APIs** tab only when a Registry is advertising via multiple IP addresses.)

**Comment by garethsb-sony** [comment]
Resolved by #39.
