### ISSUE TITLE
nmos-js only appears to be able to connect raw video or LX audio receivers and senders.

### ISSUE THREAD

**Issue by David-P-B** [sony/nmos-js#60]
When I try and connected a receiver to a sender that does not have RAW video or L24 audio, the sender is not listed as an option to connect.
I'm new to this code, can anyone suggest where in the code to look for sender type filtering for a recevier?

**Comment by garethsb** [comment]
Can you show us the Flow, Sender and Receiver pages for the ones you're trying to connect?

**Comment by David-P-B** [comment]
It appears that registery service is retruning no matching senders, so prob not an issue in nmos-js.
However, the flow media type has not been updated to to the correct media type and does not match the sender.

http://localhost:3000/#/flows
vm3/flow/v2    Video	video/raw

Sender SDP for vm3/sender/v2
v=0
o=- 3829306360 3829306360 IN IP4 192.168.10.170
s=vm3/sender/v2
t=0 0
m=video 6008 RTP/AVP 96
c=IN IP4 192.168.10.160/32
a=ts-refclk:localmac=00-00-00-00-00-17
a=mediaclk:direct=0
a=source-filter: incl IN IP4 192.168.10.160 192.168.10.170
a=rtpmap:96 H264/90000
a=fmtp:96 width=1920; height=1080; exactframerate=25; sampling=YCbCr-4:2:2; depth=10; colorimetry=BT709; TCS=SDR; PM=2110GPM; SSN=ST2110-20:2017; TP=2110TPN;
