### ISSUE TITLE
On connection to a sender, the receive port is always set to 5004, even if the receiver dst_port is another value.

### ISSUE THREAD

**Issue by David-P-B** [sony/nmos-js#61]
When I connect a receiver with e.g. a destiantion_port = 6002, the receiver port starts out as 6002, but changes to 5004.
This also happens if the sender destination port in the SDP is 6002.
I can verify the receiver dst_port is 6002 in /x-nmos/connection/v1.1/single/receivers/<receiver-id>

**Comment by garethsb** [comment]
Quoting from our Slack conversation on AMWA #nmos-community channel last week:

> I've just reconfirmed that `destination_port` is correctly picked up from `transport_params` or `transport_file` (SDP `m=` lines) in the example nmos-cpp-node and tried the nmos-js *Receiver > Staged > Edit* and *Connect* tabs and they work OK for me. Probably need to know a bit more about what you're doing differently.

**Comment by garethsb** [comment]
I suspect your Receiver starts with `auto` in **/staged**, and your Receiver resolves `auto` to `5004` on activation (this is the "default default" from the IS-05 specification, as I mentioned on Slack). In the **nmos-cpp-node** example implementation this happens at:

https://github.com/sony/nmos-cpp/blob/677fd9ddf6a11cf1fb53eddf9375e8b56d1eb83f/Development/nmos-cpp-node/node_implementation.cpp#L857

Call that function as `nmos::resolve_rtp_auto(id_type.second, transport_params, <your-preferred-default>)` to change that behaviour, as described at:

https://github.com/sony/nmos-cpp/blob/677fd9ddf6a11cf1fb53eddf9375e8b56d1eb83f/Development/nmos/connection_api.h#L76-L89

**Comment by David-P-B** [comment]
Thanks, that fixed the problem, the receiver is now getting the correct port.
