### ISSUE TITLE
Yarn Install / Build failing inside container based on Ubuntu Xenial and Disco

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-js#9]
Previously this worked with compile done on 27-Sep 2019...

Now during build inside Ubuntu Disco container the following Dockerfile command I'm getting errors. **It appears to be any issue with the new package.json under Yarn**

Am I doing something wrong now? Is there a different dependencies needed?

Thanks,
Rich.

Command:

> **RUN cd /home/ && git init && git config --global http.sslVerify false &&  git clone https://github.com/sony/nmos-js.git && cd /home/nmos-js/Development && yarn install && yarn build && cp -rf /home/nmos-js/Development/build/* /home/admin**

Output and errors:

>  ---> Running in 3a2b6bdc22e9
> Reinitialized existing Git repository in /home/.git/
> Cloning into 'nmos-js'...
> yarn install v1.19.1
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@1.2.9: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "aor-xmysql > admin-on-rest > react-router@4.1.2" has incorrect peer dependency "react@^15".
> warning "aor-xmysql > admin-on-rest > react-router-dom@4.1.2" has incorrect peer dependency "react@^15".
> warning "material-table > @date-io/date-fns@1.3.8" has incorrect peer dependency "date-fns@2.0.0-alpha.27".
> warning "material-table > @material-ui/pickers@3.2.0" has unmet peer dependency "@date-io/core@^1.3.6".
> warning " > mui-datatables@2.6.4" has incorrect peer dependency "@material-ui/core@^3.2.0".
> warning " > mui-datatables@2.6.4" has incorrect peer dependency "@material-ui/icons@^3.0.1".
> warning " > @babel/plugin-proposal-object-rest-spread@7.5.5" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "@babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning " > @babel/plugin-transform-destructuring@7.5.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "babel-eslint@10.x".
> warning " > eslint-config-react-app@4.0.1" has incorrect peer dependency "eslint-plugin-flowtype@2.x".
> warning " > eslint-plugin-flowtype@3.12.2" has incorrect peer dependency "eslint@>=6.0.0".
> [4/4] Building fresh packages...
> Done in 49.08s.
> yarn run v1.19.1
> $ react-scripts build
> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:
> 
>         ./node_modules/t-a-i/src/build.js:9
> 
> Read more here: http://bit.ly/2tRViJ9
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> The command '/bin/sh -c cd /home/ && git init && git config --global http.sslVerify false &&     git clone https://github.com/sony/nmos-js.git &&     cd /home/nmos-js/Development &&     yarn install &&     yarn build &&     cp -rf /home/nmos-js/Development/build/* /home/admin' returned a non-zero code: 1
> Makefile:9: recipe for target 'build' failed
> make: *** [build] Error 1

Additionally build fails on native Ubuntu Xenial host following yarn install / yarn build process.

> rhastie@ubuntu:~/nmos-js/nmos-js/Development$ yarn install
> yarn install v1.19.1
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@1.2.9: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "aor-xmysql > admin-on-rest > react-router@4.1.2" has incorrect peer dependency "react@^15".
> warning "aor-xmysql > admin-on-rest > react-router-dom@4.1.2" has incorrect peer dependency "react@^15".
> warning "material-table > @date-io/date-fns@1.3.8" has incorrect peer dependency "date-fns@2.0.0-alpha.27".
> warning "material-table > @material-ui/pickers@3.2.0" has unmet peer dependency "@date-io/core@^1.3.6".
> warning " > mui-datatables@2.6.4" has incorrect peer dependency "@material-ui/core@^3.2.0".
> warning " > mui-datatables@2.6.4" has incorrect peer dependency "@material-ui/icons@^3.0.1".
> warning " > @babel/plugin-proposal-object-rest-spread@7.5.5" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "@babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning " > @babel/plugin-transform-destructuring@7.5.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "babel-eslint@10.x".
> warning " > eslint-config-react-app@4.0.1" has incorrect peer dependency "eslint-plugin-flowtype@2.x".
> warning " > eslint-plugin-flowtype@3.12.2" has incorrect peer dependency "eslint@>=6.0.0".
> [4/4] Building fresh packages...
> Done in 37.43s.
> rhastie@ubuntu:~/nmos-js/nmos-js/Development$ yarn build
> yarn run v1.19.1
> $ react-scripts build
> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:
> 
>         ./node_modules/t-a-i/src/build.js:9
> 
> Read more here: http://bit.ly/2tRViJ9
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> rhastie@ubuntu:~/nmos-js/nmos-js/Development$

Am i doing something wrong now? Is there a change to the build process? Am I missing a dependency?

Thanks,
Rich,

**Comment by garethsb-sony** [comment]
Yes, sorry, we missed that `t-a-i` requires a dependency version up. This will be addressed by PR #8, which we hope to have finalised later today! (Also getting Travis CI sorted, so we'll pick build issues up faster!)

**Comment by garethsb-sony** [comment]
Hi Rich, those changes are now merged to master. Please let us know if this does(n't) solve your trouble. Thanks!

**Comment by rhastie** [comment]
Get thanks... It's building now. :)
